project:
  type: website

website:
  title: "Landschaftsökologie Bauer"
  back-to-top-navigation: true
  search: false
  navbar:
    background: "#0d730d"
    foreground: "white"
    color: "white"
    right:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "Research"
        href: index.qmd#sec-research
      - text: "Publications"
        href: index.qmd#sec-publications
      - text: "Vegetationskartierung"
        href: index.qmd#sec-loekb
      - text: "Referenzen"
        href: index.qmd#sec-referenzen
      - text: "Kontakt"
        href: index.qmd#sec-kontakt
      - icon: github
        href: "https://github.com/markus1.bauer"
  page-footer:
    right:
      - text: "(C) Markus Bauer, Germany; Made with [Quarto](https://quarto.org/)"
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd
  

format:
  html:
    fontsize: 12pt
    monofont: Arial
    toc: FALSE
    