project:
  type: website

website:
  title: "Landschaftsökologie Bauer"
  title-block-banner: images/Glatthaferwiese.jpg
  back-to-top-navigation: true
  search: false
  navbar:
    background: transparent
    foreground: "#000000"
    left:
      - icon: house-door-fill
        text: " "
        href: index.qmd
      - text: "Research"
        href: index.qmd#sec-research
      - text: "Vegetationskartierung"
        href: index.qmd#sec-loekb
    right:
      - icon: github
        href: "https://github.com/markus1.bauer"
  page-footer:
    right:
      - text: "This page is built with Quarto (https://quarto.org/)"
      - text: "Impressum"
        href: impressum.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd
  

format:
  html:
    fontsize: 12pt
    monofont: Arial
    css: styles.css
    toc: FALSE
    